//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackboneCRUD {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackboneCRUD.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldnt complete operation.
        /// </summary>
        internal static string JobController_AddData_CouldntCompleteOperation {
            get {
                return ResourceManager.GetString("JobController_AddData_CouldntCompleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job added successfully.
        /// </summary>
        internal static string JobController_AddData_JobAddedSuccessfully {
            get {
                return ResourceManager.GetString("JobController_AddData_JobAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was asked to delete job with null id.
        /// </summary>
        internal static string JobController_AddData_WasAsked2DeleteJobWithNoId {
            get {
                return ResourceManager.GetString("JobController_AddData_WasAsked2DeleteJobWithNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying to retrieve jobs.
        /// </summary>
        internal static string JobRepository_RetrieveJobs_Error {
            get {
                return ResourceManager.GetString("JobRepository_RetrieveJobs_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying to save job.
        /// </summary>
        internal static string JobRepository_Save_Error {
            get {
                return ResourceManager.GetString("JobRepository_Save_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added.
        /// </summary>
        internal static string TimeEntryController_SuccessfullyAdded {
            get {
                return ResourceManager.GetString("TimeEntryController_SuccessfullyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving time entry.
        /// </summary>
        internal static string TimeEntryRepository_ErrorSavingTimeEntry {
            get {
                return ResourceManager.GetString("TimeEntryRepository_ErrorSavingTimeEntry", resourceCulture);
            }
        }
    }
}
